<a href="https://colab.research.google.com/github/jpvillarar/TSI-PAII/blob/master/Unidad_1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Creacion de arreglos
1. Generar un arreglo cuya forma sea = (2,3,4)

In [ ]:
import numpy as np

a = np.array([[[1,2,3,4],
               [2,3,4,5],
               [7,6,4,5]],
              [[1,2,3,4],
               [2,3,4,5],
               [7,6,4,5]]])

b = np.random.randint(100,size=(2,3,4))

c = np.zeros((2,3,4))
d = np.ones((2,3,4))
print(a)
print(b)
print(c)
print(d)

[[[1 2 3 4]
  [2 3 4 5]
  [7 6 4 5]]

 [[1 2 3 4]
  [2 3 4 5]
  [7 6 4 5]]]
[[[36 18 63  9]
  [28 92 34 19]
  [84 84 58  4]]

 [[72 79 52 15]
  [35 81 53 38]
  [31 49 50 45]]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


## 2. En base a los siguientes array, obtener:
* el valor del elemento que ocupe la cuarta columna de 2 fila de la segunda dim
* los indices pares de la segunda dim
* los valores pares de la primer dim
* los elementos que sean mayores que 20


In [ ]:
x = np.random.randint(100,size=(2,3,4))
print(x)

[[[84 13 19 16]
  [15 63 82 55]
  [65 14 12 78]]

 [[87 27 69 82]
  [75 18 85 48]
  [ 1 67 97 69]]]


In [ ]:
print(x[1][1][3])
print(x[1][::2,::2])
print(x[0][x[0]%2==0]) #esto no es slicing, sino que es filtrado del arreglo
print(x[x>20])

48
[[87 69]
 [ 1 97]]
[84 16 82 14 12 78]
[84 63 82 55 65 78 87 27 69 82 75 85 48 67 97 69]


3) Calcular la suma, min, max, mean de cada array

In [ ]:
print(x.sum())
print(x.min())
print(x.max())
print(x.mean())

1241
1
97
51.708333333333336


4. Reshape de un arreglo
Crear un arreglo de 12 elementos y reconfigurarlo en una matriz (3,4)

In [ ]:
f = np.arange(12)
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
f = f.reshape((3,4))
print(f)
#reshape(2,8) # no se puede cambiar la forma de la matriz a una que tenga un tamaño distinto


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


5. Transposición de una matriz
Crea una matriz 3x2 y calcula su transposición.

In [ ]:
m = np.array([[1,2],
              [3,4],
              [5,6]])
t = m.T
print(t.shape)

(2, 3)


6. En un arreglo (10,10), quedarse con las filas pares y las columnas impares

In [ ]:
d = np.arange(100).reshape((10,10))
print(d)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [ ]:
e = d[::2,1::2]
print(e)

[[ 1  3  5  7  9]
 [21 23 25 27 29]
 [41 43 45 47 49]
 [61 63 65 67 69]
 [81 83 85 87 89]]


7. En un arreglo (5,5), quedarse con una submatriz (3,3). Pero que arranque en la 2 fila y en la 3 columna

In [ ]:
h = np.random.randint(100,size=(5,5))
h

array([[78, 84, 22, 98, 82],
       [40, 70, 78, 17, 73],
       [68, 90, 59, 95, 47],
       [62, 87,  2, 24, 87],
       [85, 50, 77, 28, 41]])

In [ ]:
print(h[1:4:,2::])

[[78 17 73]
 [59 95 47]
 [ 2 24 87]]


8. crear dos arreglos de 10 elementos cada uno y concatenarlos

In [ ]:
#(2,10)
a = np.arange(10)
b = np.arange(20,30)
print(np.vstack((a,b)))
#(10,2)
print(np.hstack((a,b)))
print(np.hstack((a.T,b.T)).shape) # esto esta mal porque al trasponer genero arreglos (10,) y al apilar resultan en un (20,)
print(np.column_stack((a.T,b.T)).shape)#column_stack si crea un arreglo con las columnas apiladas


[[ 0  1  2  3  4  5  6  7  8  9]
 [20 21 22 23 24 25 26 27 28 29]]
[ 0  1  2  3  4  5  6  7  8  9 20 21 22 23 24 25 26 27 28 29]
(20,)
(10, 2)


In [ ]:
x = np.random.randint(10,size=(3,3))+1
y = np.random.randint(10,size=(1,3))+1
print(x)
print(y)

[[ 1 10  9]
 [ 7  8  3]
 [ 3  6  3]]
[[3]
 [7]
 [2]]


In [ ]:
x+y

array([[ 4, 13, 12],
       [14, 15, 10],
       [ 5,  8,  5]])

9.
Calcular la suma de los últimos 6 valores de x con los primeros 8 de y

Calcular la suma total de los valores en índices impares de x

In [ ]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
y = np.array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

print(x[5:].sum()+y[:8].sum())
print(x[1::2].sum())

156
30


10. Realizar el producto matricial entre dos matrices A y B

In [ ]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

print(A*B)

[[ 5 12]
 [21 32]]


11. Construir un arreglo v de forma (10, 2) usando x e y, y calcular el promedio por fila y columna

In [ ]:
v = np.vstack((x,y))
print(v)
# print(v[0].mean()) #promedio de la fila 0
# print(v[1].mean()) #promedio de la fila 1

print(v.mean(axis=1))#eje 1 = filas
print(v.mean(axis=0))#eje 0 = columnas

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
6.0
[ 5.5 15.5]
[ 6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]


12. Ordenar el arreglo x de forma descendente

In [ ]:
z = sorted(x,reverse=True) # retorna un arreglo ordenado
print(z)
z.sort() #ordena el arreglo
print(z)

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


13. Definir una funcion que calcule la media por columna de una matriz solo si la matriz tiene numero par de filas. En el caso de que la matriz sea 3D, calcular la media por columna dentro de cada dimension

In [ ]:
def funcion(matriz):
  resultado = []
  if len(matriz.shape)>2:
    if matriz.shape[1] %2==0:
      for i in matriz:
        resultado.append(i.mean(axis=0))
    else: print("tiene cantidad de filas impar")
  elif len(matriz.shape)==2:
    if matriz.shape[0] %2==0:
      resultado = matriz.mean(axis=0)
    else: print("tiene cantidad de filas impar")
  else: print("la matriz es unidimensional")
  return resultado


In [ ]:
#matriz = np.random.randint(10,size=(2,3))
print(matriz)
len(matriz.shape)

[[5 7 2]
 [7 3 9]]


2

In [ ]:
matriz2 = np.random.randint(10,size=(2,2,3))
print(matriz2)
len(matriz2.shape)
#funcion(matriz2)
print(funcion(matriz2))

[[[5 7 6]
  [5 7 2]]

 [[1 3 1]
  [7 1 2]]]
[array([5., 7., 4.]), array([4. , 2. , 1.5])]


14. Definir una funcion que guarde solo los valores de las filas impares de una matriz tridimensional, guarde las filas impares de cada dimension en una matriz temporal y devuelva como resultado la concatenacion vertical de estas filas

In [ ]:
matriz2

array([[[7, 1, 3],
        [1, 4, 5]],

       [[6, 3, 1],
        [9, 9, 3]]])

In [ ]:
def filas_impares(matriz):
  lista = []
  if len(matriz.shape)==3:
    for i in matriz:
      lista.append(i[1::2])
    resultado = np.vstack(lista)
  return resultado

In [ ]:
filas_impares(matriz2)

array([[1, 4, 5],
       [9, 9, 3]])

15. Definir una funcion que reemplace todos los valores en la ultima dimension por un valor determinado que sean menores que un numero determinado

In [ ]:
def reemplazo(matriz,minimo,reemplazo):
  matriz_copy = matriz.copy() #devuelve una copia de mi objeto original
  matriz_copy[-1][matriz_copy[-1]<minimo] = reemplazo
  return matriz_copy

In [ ]:
matriz3 = reemplazo(matriz2,5,-3)
print(matriz2)
print(matriz3)

[[[ 5  7  6]
  [ 5  7  2]]

 [[-3 -3 -3]
  [ 7 -3 -3]]]
[[[ 5  7  6]
  [ 5  7  2]]

 [[-3 -3 -3]
  [ 7 -3 -3]]]


In [ ]:
matriz3 = matriz2[-1]
matriz3[matriz3<5] = -3
matriz4 = matriz3[1::2]
print(matriz2)
print(matriz4)

[[[ 5  7  6]
  [ 5  7  2]]

 [[-3 -3 -3]
  [ 7 -3 -3]]]
[[ 7 -3 -3]]
